print("Hello World!")
print("I am learning Python.")
print("It is awesome!")
print("this will work!")
print('this will also work!')
print("hello world!",end="")
print("i will print on the same line.")
print(3)
print(358)
print(50000)